name: Docker Image Build For XRootD Stageout Server SDN

on:
  workflow_dispatch:
    inputs:
      buildtag:
        description: "Build Tag"
        default: "dev"
        type: "string"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      DOCKER_REGISTRY: ${{secrets.DOCKER_REGS}}
      DOCKER_SDN_USER: ${{secrets.DOCKER_SDN_USER}}
      DOCKER_SDN_PASSWORD: ${{secrets.DOCKER_SDN_PASSWORD}}
      DOCKER_SDN_REGISTRY: ${{secrets.DOCKER_SDN_REGS}}
      DOCKER_TIER2_USER: ${{secrets.DOCKER_TIER2_USER}}
      DOCKER_TIER2_PASSWORD: ${{secrets.DOCKER_TIER2_PASSWORD}}
      DOCKER_TIER2_REGISTRY: ${{secrets.DOCKER_TIER2_REGS}}
      IMAGE_NAME: "cmscaltech/xrootd-stageout-server-sdn"
    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: cmscaltech/docker
        path: cmscaltech-docker

    - name: docker login
      run: |
        docker login $DOCKER_REGISTRY -u $DOCKER_USER --password-stdin $DOCKER_PASSWORD
        docker login $DOCKER_SDN_REGISTRY -u $DOCKER_SDN_USER --password-stdin $DOCKER_SDN_PASSWORD
        docker login $DOCKER_TIER2_REGISTRY -u $DOCKER_TIER2_USER --password-stdin $DOCKER_TIER2_PASSWORD
    - name: Build Docker image
      run: |
        cd cmscaltech-docker/xrootd/xrootd-stageout-server-sdn/
        docker build . --file Dockerfile \
            --tag $IMAGE_NAME:${{ github.event.inputs.buildtag }} \
            --tag $IMAGE_NAME:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d) \
            --tag $DOCKER_SDN_REGISTRY/$IMAGE_NAME:${{ github.event.inputs.buildtag }} \
            --tag $DOCKER_SDN_REGISTRY/$IMAGE_NAME:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d) \
            --tag $DOCKER_TIER2_REGISTRY/$IMAGE_NAME:${{ github.event.inputs.buildtag }} \
            --tag $DOCKER_TIER2_REGISTRY/$IMAGE_NAME:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push Image to first registry
      run: |
        docker push $IMAGE_NAME:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)
        docker push $IMAGE_NAME:${{ github.event.inputs.buildtag }}

    - name: Docker Push Image to second registry
      run: |
        docker push $DOCKER_SDN_REGISTRY/$IMAGE_NAME:${{ github.event.inputs.buildtag }}
        docker push $DOCKER_SDN_REGISTRY/$IMAGE_NAME:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push Image to third registry
      run: |
        docker push $DOCKER_TIER2_REGISTRY/$IMAGE_NAME:${{ github.event.inputs.buildtag }}
        docker push $DOCKER_TIER2_REGISTRY/$IMAGE_NAME:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)
